pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/AbednegoTenge/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app/messaging_app') {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app/messaging_app') {
                    sh '''
                    . venv/bin/activate
                    pytest --html=report.html --self-contained-html
                    '''
                }
            }
        }
    }

    post {
        always {
            dir('messaging_app/messaging_app') {
                archiveArtifacts artifacts: 'report.html', fingerprint: true
            }
        }
    }
    
}

