pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/AbednegoTenge/alx-backend-python.git'
            }
        }

        stage('Install Dependencies and run tests') {
            steps {
                dir('messaging_app/messaging_app') {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install -r requirements.txt
                    pytest --html=report.html --self-contained-html
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('messaging_app') {
                    sh '''
                    docker build -t abednegotenge/messaging_app:latest .
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdn
                    docker push abednegotenge/messaging_app:latest
                    '''
                }
            }
        }
    }

    post {
        always {
            dir('messaging_app/messaging_app') {
                archiveArtifacts artifacts: 'report.html', fingerprint: true
            }
        }
    }
    
}

