#!/bin/bash

echo "----kuberScript: Kubernetes Cluster Starter----"

# check that Minikube is installed
if ! command -v minikube >/dev/null 2>&1; then
	echo "Minikube is not installed"
	echo "Please install minikube first:"
	echo "https://minikube.sigs.k8s.io/docs/start/"
	exit 1
else
	echo "Minikube is installed"
fi


# start the kubernetes cluster
echo "⏳ starting Minikube..."
minikube start --driver=docker
minikube start

if [ $? -ne 0 ]; then
	echo "Failed to start minikube cluster"
	exit 1
fi
echo "Minikube cluster started successfully"


# verify the cluster is running
echo "⏳ verifying the cluster is running"
kuberctl cluster-info

if [$? -ne 0 ]; then
	echo "kubernetes cluster is not running"
	exit 1
fi
echo "kubernetes cluster is running"

# retrieve available pods
echo "⏳ retrieving available pods"
kuberctl get pods --all-namespaces

echo "----kuberscript completed successfully"
