# Generated by Django 5.2.8 on 2025-11-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
    ]
