apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
  labels:
    app: django-messaging
spec:
  type: ClusterIP
  selector:
    app: django-messaging
    version: blue  # Switch this to 'green' to route traffic to green deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
---
# Alternative: Service that routes to both versions (for testing)
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service-all
  labels:
    app: django-messaging
spec:
  type: ClusterIP
  selector:
    app: django-messaging
    # No version selector - routes to all pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
